POST localhost:8081/student/create
Content-Type: application/json

{
  "name": "Ramziddin",
  "surname": "Rustamov",
  "age": 34
}

### get all student

GET localhost:8081/student/all

### get by id
GET  localhost:8081/student/9